== アップグレード互換性の検証

目標：以下が発生することなくアップグレードを進められることを検証する必要があります。

* クライアントの破壊（Candid インターフェースの変更に起因）
* Motoko のステーブルステートを破棄する（ステーブル宣言の変更に起因）

Motokoでは、これらの性質を（アップグレードを試みる前に）静的にチェックすることを約束しています。

その約束が果たされる様子を見ていきましょう。

=== ステーブルでないカウンタ

以下は、ステートフルなカウンタを宣言する簡単な例です。

[source.no-repl, motoko]
....
include::../examples/count-v0.mo[]
....

残念ながら、このカウンタを（例えば同じコードで）アップグレードすると、ステートが失われてしまいます。

|===
| バージョン | ステート | 成功 | コール
| v0 | 0 | &check; | inc()
| v0 | 1 | &check; | inc()
| v0 | 2 | &check; | upgrade(v0)
| v0 | #0# | #&cross;#  | inc()
| v0 | 1 |  |
|===

=== ステーブルなカウンタ

Motoko では、変数を（アップグレードをまたいで）+stable+ と宣言することができます。

[source.no-repl, motoko]
....
include::../examples/count-v1.mo[]
....

`stable` なので、このカウンタのステート（`state`）はアップグレードしても _保持_ されます。

（`stable` とマークされていない場合、アップグレード時に `state` は `0` に初期化されます。）

|===
| バージョン | ステート | 成功 | コール
| v1 | 0 | &check; | inc()
| v1 | 1 | &check; | inc()
| v1 | 2 | &check; | upgrade(v1)
| v1 | 2 | #&check;# | inc()
| v1 | 3 | |
|===


=== Candid インターフェースを更新する

API を拡張しましょう。
古いクライアントは引き続き動作するようにし、新しいクライアントは追加の機能（`read` クエリ）を獲得します。

[source.no-repl, motoko]
....
include::../examples/count-v2.mo[]
....


|===
| バージョン | ステート | 成功 | コール
| v1 | 3 | &check; | inc()
| v1 | 4 | &check; | upgrade(v2)
| v2 | 4 | #&check;# | inc()
| v2 | 5 | &check; | read()
|===

=== ステーブルインターフェースを更新する

注目：カウンタは常に正の数です。`Int` を `Nat` にリファクタリングしましょう！

[source.no-repl, motoko]
....
include::../examples/count-v3.mo[]
....

|===
| バージョン | ステート | 成功 | コール
| v2| 5 | &check; |  inc()
| v2 | 6  | &check; | upgrade(v3)
| v3 | #0# | #&cross;# | inc()
| v3 | 1 | &check; | read()
|===

ドーン：コードはアップグレードされましたが、カウンタが `0` に戻ってしまいました。

_考えられない事態が発生しました_。アップグレードでステートが失われたのです。

=== 何が起こった？

Candid インターフェースは安全に更新されましたが… ステーブル型は安全に更新されませんでした。

アップグレードは、以下を必ず実行しなければなりません。

* ステーブル変数の値をアップグレード前のものから受け取る。
* 新しいステーブル変数の初期化を実行する。

`Int </: Nat` なので、アップグレードのロジックは保存されていた `Int` を破棄し（例えばそれが `-1` だったらどうでしょう？）、代わりに初期化ロジックを再実行します。

さらに悪いことに、アップグレードは静かに成功し、カウンタを `0` にリセットします。

=== ステーブル型のシグネチャ

ステーブル型のシグネチャは、Motoko の Actor 型の中身のようなものです。

例えば、``v2`` のステーブル型は以下の通りです。

[source.no-repl, motoko]
....
include::../examples/count-v2.most[]
....

``v2`` からアップグレードされた ``v3`` のステーブル型は以下の通りです。

[source.no-repl, motoko]
....
include::../examples/count-v3.most[]
....

上記は `Int` を `Nat` として受け取ることを要求されますが、これは #*型エラー*# です。

=== ２ つのインターフェースの同時更新

アップグレードが安全であることは、以下の条件が必要です。

* Candid インターフェースがサブタイプに更新されること。
* ステーブルインターフェースが互換性のあるもの（スーパータイプまたは新規の変数）に更新されること。

[cols="1,5,5"]
|===
| バージョン
| Candid インターフェース
| ステーブル型インターフェース

| v0
a|
[source.no-repl, candid]
....
include::../examples/count-v0.did[]
....
a|
[source.no-repl, motoko]
....
include::../examples/count-v0.most[]
....

|
| +:>+ &check;
| +<<:+ &check;

| v1
a|
[source.no-repl, candid]
....
include::../examples/count-v1.did[]
....
a|
[source.no-repl, motoko]
....
include::../examples/count-v1.most[]
....

|
| +:>+ &check;
| +<<:+ &check;

| v2
a|
[source.no-repl, candid]
....
include::../examples/count-v2.did[]
....
a|
[source.no-repl, motoko]
....
include::../examples/count-v2.most[]
....

|
| +:>+ &check;
| +<<:+ #&cross;#

| v3
a|
[source.no-repl, candid]
....
include::../examples/count-v3.did[]
....
a|
[source.no-repl, motoko]
....
include::../examples/count-v3.most[]
....
|===

=== ツール

Motoko コンパイラ (`moc`) は以下をサポートするようになりました。

* `moc --stable-types ...` は、ステーブル型を `.most` ファイルに出力します。
* `moc --stable-compatible <pre> <post>` は、2 つの `.most` ファイルをチェックし、アップグレードの互換性を確認します。

`cur.wasm` から `nxt.wasm` にアップグレードするには、Candid インターフェースと ステーブル変数の +両方+ に互換性があることを確認する必要があります。

[source.no-repl]
....
didc check nxt.did cur.did  // nxt <: cur
moc --stable-compatible cur.most nxt.most  // cur <<: nxt
....

例えば、`v2` から `v3` へのアップグレードは、チェックを行うと失敗します。

[source.no-repl]
....
> moc --stable-compatible v2.most v3.most
(unknown location): Compatibility error [M0170], stable variable state of previous type
  var Int
cannot be consumed at new type
  var Nat
....

=== 参考例

https://forum.dfinity.org/t/questions-about-data-structures-and-migrations/822/12?u=claudio

|===
a|[source.no-repl, motoko]
....
type Card = {
  title : Text
};
actor {
  stable var map: [(Nat32, Card)]
}
....
| <<: #&cross;#
a|[source.no-repl, motoko]
....
type Card = {
  title : Text;
  description : Text
};
actor {
  stable var map : [(Nat32, Card)]
}
....
|===

（何もないところから魔法のように）新しいレコードフィールドを追加するのは悪いことです。

=== メタデータセクション

Motoko は `.did` と `.most` ファイルを WASM の _カスタムセクション_ として埋め込み、dfx などの他のツールで使用できるようにしています。

将来的には、`dfx canister upgrade` は、デフォルトで次のような動作を行うようになります。

1. Canister の 2 つのインターフェースについて IC に問い合わせる。
2. インストールされたバイナリと新しいバイナリの互換性をチェックする。
3. 安全でない場合はアップグレードを中止する。

=== なぜ今になってデータロスが発生しているのか？

（変数のステーブル化のための）Candid に対する改訂の副作用です。

* 以前は、`v2.wasm` から `v3.wasm` へのアップグレードは失敗してロールバックしていました（データ損失なし）。
* Candid の改訂によって、アップグレードが成功する代わりにデータ損失が生じるようになっています。

（"フェイルセーフ" 対 "サイレント障害"）

=== 正しい解決策

実際に `state` を `Nat` に変更したい場合はどうすればよいのでしょうか。

解決策：新しいステーブル変数 `newState` を導入し、古い変数を用いて初期化します。

[source.no-repl, motoko]
....
include::../examples/count-v4.mo[]
....


[source.no-repl, motoko]
....
include::../examples/count-v4.most[]
....

（もしくは最初からバリアントを使いましょう…）

////
== Verifying upgrade compatibility

Goal: we need to verify that an upgrade can proceed without:

* breaking clients (due to a Candid interface change)
* discarding Motoko stable state (due to a change in stable declarations)

With Motoko, we promised to check these properties statically
(before attempting the upgrade).

Let's deliver on that promise.

=== An unstable counter

The following is a simple example of how to declare a stateful counter.

[source.no-repl, motoko]
....
include::../examples/count-v0.mo[]
....

Unfortunately, when we upgrade this counter (say with itself), its state is lost.

|===
| version | state | success | call
| v0 | 0 | &check; | inc()
| v0 | 1 | &check; | inc()
| v0 | 2 | &check; | upgrade(v0)
| v0 | #0# | #&cross;#  | inc()
| v0 | 1 |  |
|===

=== A stable counter

In Motoko, we can declare variables to be +stable+ (across upgrades).

[source.no-repl, motoko]
....
include::../examples/count-v1.mo[]
....

Because it's `stable`, this counter's `state` is _retained_ across upgrades.

(If not marked `stable`, `state` would restart from `0` on upgrade).

|===
| version | state | success | call
| v1 | 0 | &check; | inc()
| v1 | 1 | &check; | inc()
| v1 | 2 | &check; | upgrade(v1)
| v1 | 2 | #&check;# | inc()
| v1 | 3 | |
|===


=== Evolving the Candid interface:

Let's extend the API - old clients still satisfied, new ones get
extra features (the `read` query).

[source.no-repl, motoko]
....
include::../examples/count-v2.mo[]
....


|===
| version | state | success | call
| v1 | 3 | &check; | inc()
| v1 | 4 | &check; | upgrade(v2)
| v2 | 4 | #&check;# | inc()
| v2 | 5 | &check; | read()
|===

=== Changing the stable interface

Observation: the counter is always positive - let's refactor `Int` to `Nat`!

[source.no-repl, motoko]
....
include::../examples/count-v3.mo[]
....

|===
| version | state | success | call
| v2| 5 | &check; |  inc()
| v2 | 6  | &check; | upgrade(v3)
| v3 | #0# | #&cross;# | inc()
| v3 | 1 | &check; | read()
|===

BOOM: code upgraded, but counter is back to `0`.

_The unthinkable has happened_: state was lost in an upgrade.

=== What gives?

The Candid interface evolved safely ... but the stable types did not.

An upgrade must be able to:

* consume any stable variable value from its predecessor, or
* run the initializer for a new stable variable.

Since `Int </: Nat`, the upgrade logic discards the saved `Int` (what if it was `-1`?) and re-runs the initializer instead.

What's worse, the upgrade silently "succeeded", resetting the counter to `0`.

=== Stable type signatures

A stable type signature looks like the "insides" of a Motoko actor type.

For example, ``v2``'s stable types:

[source.no-repl, motoko]
....
include::../examples/count-v2.most[]
....

An upgrade from ``v2`` to ``v3``'s stable types:
[source.no-repl, motoko]
....
include::../examples/count-v3.most[]
....

requires consuming an `Int` as a `Nat`: a #*type error*#.

=== Dual interface evolution

An upgrade is safe provided:

* the candid interface evolves to a subtype; and
* the stable interface evolves to a compatible one (variable to supertype or new)

[cols="1,5,5"]
|===
| version
| candid interface
| stable type interface

| v0
a|
[source.no-repl, candid]
....
include::../examples/count-v0.did[]
....
a|
[source.no-repl, motoko]
....
include::../examples/count-v0.most[]
....

|
| +:>+ &check;
| +<<:+ &check;

| v1
a|
[source.no-repl, candid]
....
include::../examples/count-v1.did[]
....
a|
[source.no-repl, motoko]
....
include::../examples/count-v1.most[]
....

|
| +:>+ &check;
| +<<:+ &check;

| v2
a|
[source.no-repl, candid]
....
include::../examples/count-v2.did[]
....
a|
[source.no-repl, motoko]
....
include::../examples/count-v2.most[]
....

|
| +:>+ &check;
| +<<:+ #&cross;#

| v3
a|
[source.no-repl, candid]
....
include::../examples/count-v3.did[]
....
a|
[source.no-repl, motoko]
....
include::../examples/count-v3.most[]
....
|===

=== Tooling

Motoko compiler (`moc`) now supports:

* `moc --stable-types ...` emits stable types to a `.most` file
* `moc --stable-compatible <pre> <post>` checks two `.most` files for upgrade compatibility

To upgrade from `cur.wasm` to `nxt.wasm` we need check +both+ Candid interface and stable variables are "compatible"

[source.no-repl]
....
didc check nxt.did cur.did  // nxt <: cur
moc --stable-compatible cur.most nxt.most  // cur <<: nxt
....

E.g. the upgrade from `v2` to `v3` fails this check:

[source.no-repl]
....
> moc --stable-compatible v2.most v3.most
(unknown location): Compatibility error [M0170], stable variable state of previous type
  var Int
cannot be consumed at new type
  var Nat
....

=== Examples in the wild


https://forum.dfinity.org/t/questions-about-data-structures-and-migrations/822/12?u=claudio

|===
a|[source.no-repl, motoko]
....
type Card = {
  title : Text
};
actor {
  stable var map: [(Nat32, Card)]
}
....
| <<: #&cross;#
a|[source.no-repl, motoko]
....
type Card = {
  title : Text;
  description : Text
};
actor {
  stable var map : [(Nat32, Card)]
}
....
|===


Adding a new record field (to magic from nothing) is bad.

=== Metadata Sections

Motoko embeds `.did` and `.most` files as wasm _custom sections_, for use by other tools, e.g. dfx.

In future, `dfx canister upgrade` will, by default:

1. query the IC for a canister's dual interfaces,
2. check compatibility of the installed and new binary,
3. abort the upgrade when unsafe.


=== Why are we seeing data-loss only now?

A side-effect of a revision to Candid (used for stabilizing variables):

* Previously, upgrades from `v2.wasm` to `v3.wasm` would fail and roll-back (no data loss).
* Candid revision meant upgrade would now "succeed", but _with_ data loss.

("fail safe" vs "silent failure")

=== The right solution

What if we really do want to change `state` to `Nat`.

Solution: introduce a new stable variable, `newState`, initialized from the old one:

[source.no-repl, motoko]
....
include::../examples/count-v4.mo[]
....


[source.no-repl, motoko]
....
include::../examples/count-v4.most[]
....

(Or use a variant from the start...)

////