= イントロダクション
:proglang: Motoko
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

{proglang} は、link:../developers-guide/concepts/what-is-ic{outfilesuffix}#ic-overview[Internet Computer] 上で動作するスマートコントラクトの Canister の開発に特化した、最新の汎用プログラミング言語です。
この言語は {IC} を直接のターゲットにしていますが、将来的に他のターゲットへのコンパイルをサポートするのに十分な程度には一般的な設計になっています。

== アプローチ性（言語の親しみやすさ）

{proglang} は、JavaScript、Rust、Swift、TypeScript、C#、Java などのモダンプログラミング言語を通してオブジェクト指向や関数型プログラミングのイディオムに基本的な知識を持っているプログラマーが親しみやすいように設計されたモダン言語です。

== 非同期メッセージングと型安全な実行

{proglang} は、分散型アプリケーション（Dapps）のための特別なプログラミング抽象化を含む、モダンプログラミングのイディオムを使用可能にしています。
それぞれの Dapps は、非同期のメッセージパッシングのみで通信する、1つまたは複数の _Actor_ で構成されます。Actor のステートは、他のすべての Actor から分離されており、分散性をサポートしています。複数の Actor 間でステートを共有する方法はありません。
{proglang} の Actor ベースのプログラミングの抽象化は、人間が読めるメッセージパッシングのパターンによってプログラミングすることを可能にし、各ネットワークの相互作用が特定のルールに従うことや、よくある間違いを避けることを強制します。

具体的には、{proglang} プログラムは実行前に各プログラムをチェックする実用的でモダンな型システムが含まれているため、_型健全_ です。
{proglang} の型システムは、{proglang} のプログラムが、可能なすべての入力に対して動的な型エラーを起こさずに安全に実行されるかどうかを静的にチェックします。
その結果、他の言語、特に Web プログラミング言語でよく見られるプログラミング上の落とし穴の類の全てが除外されます。これには、NULL 参照エラー、引数や返り値の型のミスマッチ、フィールドの欠落エラーなどが含まれます。

実行時には、{proglang} は、link:about-this-guide{outfilesuffix}#wasm[WebAssembly] という、モダンコンピュータハードウェアをきれいに抽象化したポータブルなバイナリフォーマットに静的にコンパイルし、インターネット上で広く実行したり、link:.../developers-guide/concepts/what-is-ic{outfilesuffix}#ic-overview[{IC}] 上で実行したりすることを可能にしています。

[[pitch-actors]]
== _Actor_ としての各 Canister スマートコントラクト

{proglang} は、link:../developers-guide/concepts/what-is-ic{outfilesuffix}#ic-overview[{IC}] 上の Canister スマートコントラクトのものを含む Service を表現するための *Actor ベース* のプログラミングモデルを開発者に提供しています。

Actor はオブジェクトに似ていますが、そのステートが完全に分離されており、世界中とのやりとりがすべて _非同期_ メッセージングで行われる点が特別です。

Actor との間のすべてのコミュニケーションは、{IC} のメッセージングプロトコルを使い、ネットワーク上で非同期にメッセージを渡しています。
Actor のメッセージは順番に処理されるので、ステートの変更が競合状態を認めることはありません（`await` の区切りで明示的に許可されている場合を除く）。

{IC} は、送信された各メッセージが確実に応答を受け取ることを保証します。レスポンスは、ある値を持つ成功ステータスか、エラーのいずれかです。エラーには、受信側の Canister による明示的なメッセージの拒否、ゼロ除算などの不正な命令によるトラップ、配布やリソースの制約によるシステムエラーなどがあります。例えば、システムエラーとは、受信者が一時的または恒久的に利用できないことです（受信 Actor にアクセス集中しているか、削除されているかのいずれか）。

[[pitch-async-actors]]
=== 非同期 Actor

他の _モダン_ プログラミング言語と同様に、{proglang} はコンポーネント間の _非同期_ コミュニケーションのための人間工学的なシンタックスを認めています。

{proglang} の場合、通信している各コンポーネントが Actor です。

Actor を _使う_ 例として（おそらく自分自身も _Actor_ だと考えるのがよいでしょう）、この3行のプログラムを考えてみましょう。

[source.no-repl, motoko]
....
let result1 = service1.computeAnswer(params);
let result2 = service2.computeAnswer(params);
finalStep(await result1, await result2)
....

このプログラムの動作は、3つのステップでまとめることができます：

. プログラムは、{proglang} Actor または他の言語で実装された Canister スマートコントラクトとして実装された2つの異なる Service に対して、2つのリクエスト（1行目と2行目）を行います。

. プログラムは、各返り値に対してキーワード `await` を用いて、各返り値の準備ができるのを待ちます（3行目）。

. プログラムは、最終ステップ（3行目）で `finalStep` 関数を呼び出して、両方の結果を使用します。

一般的に言えば、Service は互いに待つのではなく、実行を _インターリーブ_ することで全体の待ち時間を短縮することができます。
しかし、特別な言語サポート _なし_ にこの方法で待ち時間を短縮しようとすると、そのようなインターリーブにはすぐに明快さや単純さが犠牲となります。

インターリーブ実行が _ない_ 場合（例えば、上記の呼び出しが2つではなく1つだけの場合）でも、同じ理由で、プログラミングの抽象化によって明確さと単純さを実現しています。
つまり、プログラムを変換する場所をコンパイラに知らせることで、背後にあるシステムのメッセージパッシングループによる実行をインターリーブするために、プログラマがプログラムロジックを歪めることをせずにすみます。

このプログラムでは、3行目で `await` を使用することで、そのインターリーブ動作を　{proglang} が提供する人間が読めるシンタックスでシンプルに表現しています。

このような抽象化がなされていない言語環境では、開発者は単にこれらの2つの関数を直接呼び出すのではなく、非常に高度なプログラミングパターンを採用することになります。おそらくシステムが提供する `イベントハンドラ` の中に開発者が提供する `コールバック関数` を登録することになるでしょう。

各コールバックは、呼び出した関数の返り値の準備ができたときに発生する非同期イベントを処理することになります。このようなシステムレベルのプログラミングは強力ですが、高レベルのデータフローを、共有されているステートを通じて通信する低レベルのシステムイベントに分解することになるため、非常にエラーが発生しやすいです。
このようなプログラミングスタイルが必要な場合もありますが、ここではそうではありません。

私たちのプログラムは、このような煩雑なプログラミングスタイルを避け、代わりにより自然な _ダイレクト_ スタイルを採用しており、各リクエストは通常の関数呼び出しに近い形となっています。
この、よりシンプルで様式化されたプログラミング形式は、今日のほとんどのモダンソフトウェアがそうであるように、_外部環境_ と相互作用する実用的なシステムの表現としてますます人気が高まっています。

しかし、これには特別なコンパイラと型システムのサポートが必要で、その詳細については後述します。

[[pitch-async-behavior]]
=== _非同期_ 動作のサポート

_非同期_ コンピューティングでは、プログラムとその実行環境は、互いに _並行_ して実行される _内部計算_ を行うことができます。

具体的には、非同期プログラムとは、プログラムの実行を計算環境に要求した場合に、その完了を待つ必要が（必ずしも）ないものです。
同時に、計算環境が要求された計算を完了するまでの間、プログラムはその環境の中で内部計算を行うことが許されます。上の例では、プログラムは最初の要求が完了するのを待つ前に2番目の要求を発行します。

対称的に、環境側がプログラムに要求することは、プログラムの回答を待つことを（必ずしも）必要としません。 環境側は、プログラム側で答えが生成される間に外部で計算を進行することができます。

上では、この "`通知`" パターンの例を示していませんが、これはコールバック（および _高次_ 関数と制御フロー）を使用するため、より複雑になるからです。

[[pitch-async]]
=== `async` / `await` 構文

わかりやすさとシンプルさへのニーズに対応するために、{proglang} では急速に普及している `async` と `await` というプログラム構成を採用しています。これは、複雑になりがちな非同期の依存関係グラフを記述するための _構造化された_ 言語をプログラマにもたらします。

link:language-manual{outfilesuffix}#exp-async[async] の構文によって、Future が導入されます。 Future の値は _将来的に非同期に配信される結果の_ "`promise`" を表します（上の最初の例では示されていません）。
Future については、link:actors-async{outfilesuffix}[Actor と async データ]で Actor を導入した際により詳しく学びます。

ここでは単純に、`service1.computeAnswer(params)` と `service2.computeAnswer(params)` を呼び出した際に返ってくる値を使用します。

`await` 構文を用いると Future に同期し、その生成元によって Future が完了するまで計算を中断します。
上の例では、2 つの Service の呼び出しから結果を得るために、`await` が2つ使われています。

開発者がこれらのキーワードを使用すると、コンパイラは必要に応じてプログラムを変換します。多くの場合、純粋に同期的な言語では手作業で実行するのが面倒な、プログラムの制御フローやデータフローの複雑な変換を行います。
一方、{proglang} の型システムでは、型の生成側と使用側を流れる型は常に一致しており、Sercive 間で送信されるデータ型は行き来することが許可されていること、そして（例えば）link:mutable-state{outfilesuffix}[プライベートな可変型ステート] を含まないことなど、これらの構成要素の一定の正しい使用パターンが強制されます。

[[pitch-types]]
=== 型と Static

他のモダンプログラミング言語と同様、{proglang} では、各変数に関数やオブジェクト、プリミティブなデータ（文字列、単語、整数など）の値を入れることができます。

レコード、タプル、_バリアント_ と呼ばれる "`タグ付けされたデータ`" など、他の link:basic-concepts{outfilesuffix}#intro-values[値の型] も使用可能です。

{proglang} は、_型の健全性_ としても知られる型安全性の形式的な特性を享受しています。
この考え方は、link:basic-concepts{outfilesuffix}#intro-type-soundness[正しく型付けされた {proglang} プログラムは間違いを起こさない] というフレーズでしばしばまとめられます。これは、データに対して実行される操作は、その静的な型によって許可されるものだけであるという意味です。

例えば、{proglang} プログラムの各変数には関連する _型_ があり、この型はプログラムが実行される前に _静的に_ 知られています。
各変数の使用はコンパイラによってチェックされ、NULL 参照エラー、無効なフィールドアクセスなどの実行時の型エラーを防ぎます。

この意味で、{proglang} の型は、プログラムのソースコードの中で、_信頼できる、**コンパイラが検証した** ドキュメント_ を提供します。

通常通り、動的テストでは {proglang} の型システムの手の届かないところにあるプロパティをチェックすることができます。
{proglang} の型システムはモダンではありますが、意図的に `先進的` ではなく、特に風変わりなものでもありません。
むしろ、{proglang} の型システムは、モダンでありながら非常に理解しやすい、link:about-this-guide{outfilesuffix}#modern-types[実用的な型システム]の標準的な概念を統合し、汎用の分散アプリケーションをプログラミングするための、親しみやすく表現力豊かでありながらも安全な言語を提供しています。

////
= Introduction
:proglang: Motoko
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

{proglang} is a modern, general-purpose programming language you can use specifically to author link:../developers-guide/concepts/what-is-ic{outfilesuffix}#ic-overview[Internet Computer]  canister smart contracts.
Although aimed squarely at the {IC}, its design is general enough to support future compilation to other targets.

== Approachability

{proglang} is a modern language designed to be approachable for programmers who have some basic familiarity with modern object-oriented and/or functional programming idioms in either JavaScript, or another modern programming language, such as Rust, Swift, TypeScript, C#, or Java.

== Asynchronous messaging and type sound execution

{proglang} permits modern programming idioms, including special programming abstractions for distributed applications (dapps).
Each dapp consists of one or more  _actor_s that communicate solely by asynchronous message passing. The state of an actor is isolated from all other actors, supporting distribution. There is no way to share state between several actors. 
The actor-based programming abstractions of {proglang} permit human-readable message-passing patterns, and they enforce that each network interaction obeys certain rules and avoids certain common mistakes.

Specifically, {proglang} programs are _type sound_ since {proglang} includes a practical, modern type system that checks each one before it executes.
The {proglang} type system statically checks that each {proglang} program will execute safely, without dynamic type errors, on all possible inputs.
Consequently, entire classes of common programming pitfalls that are common in other languages, and web programming languages in particular, are ruled out. This includes null reference errors, mis-matched argument or result types, missing field errors and many others.

To execute, {proglang} statically compiles to link:about-this-guide{outfilesuffix}#wasm[WebAssembly], a portable binary format that abstracts cleanly over modern computer hardware, and thus permits its execution broadly on the Internet, and the link:../developers-guide/concepts/what-is-ic{outfilesuffix}#ic-overview[{IC}].

[[pitch-actors]]
== Each canister smart constract as an _actor_

{proglang} provides an *actor-based* programming model to developers to express _services_, including those of canister smart contracts on the link:../developers-guide/concepts/what-is-ic{outfilesuffix}#ic-overview[{IC}].

An actor is similar to an object, but is special in that its state is completely isolated, and all its interactions with the world are by _asynchronous_ messaging.

All communication with and between actors involves passing messages asynchronously over the network using the Internet Computer's messaging protocol.
An actor’s messages are processed in sequence, so state modifications never admit race conditions (unless explicitly allowed by punctuating `await`s).

The Internet Computer ensures that each message that is sent receives a response. The response is either success with some value, or an error. An error can be the explicit rejection of the message by the receiving canister, a trap due to an illegal instruction such as division by zero, or a system error due to distribution or resource constraints. For example, a system error might be the transient or permanent unavailability of the receiver (either because the receiving actor is oversubscribed or has been deleted).

[[pitch-async-actors]]
=== Asynchronous actors

Like other _modern_ programming languages, {proglang} permits an ergonomic syntax for _asynchronous_ communication among components.

In the case of {proglang}, each communicating component is an actor.

As an example of _using_ actors, perhaps as an actor ourselves, consider this three-line program:

[source.no-repl, motoko]
....
let result1 = service1.computeAnswer(params);
let result2 = service2.computeAnswer(params);
finalStep(await result1, await result2)
....

We can summarize the program's behavior with three steps:

. The program makes two requests (lines 1 and 2) to two
distinct services, each implemented as a {proglang} actor or canister smart contract implemented in some other language.

. The program waits for each result to be ready (line 3) using the keyword `await` on each result value.

. The program uses both results in the final step (line 3) by calling the `finalStep` function.

Generally-speaking, the services _interleave_ their executions rather than wait for one another, since doing so reduces overall latency.
However, if we try to reduce latency this way _without_ special language support, such interleaving will quickly sacrifice clarity and simplicity.

Even in cases where there are _no_ interleaving executions (for example, if there were only one call above, not two), the programming abstractions still permit clarity and simplicity, for the same reason.
Namely, they signal to the compiler where to transform the program, freeing the programmer from contorting the program's logic in order to interleave its execution with the underlying system's message-passing loop.

Here, the program uses `await` in line 3 to express that interleaving behavior in a simple fashion, with human-readable syntax that is provided by {proglang}.

In language settings that lack these abstractions, developers would not merely call these two functions directly, but would instead employ very advanced programming patterns, possibly registering developer-provided "`callback functions`" within system-provided "`event handlers`".
Each callback would handle an asynchronous event that arises when an answer is ready.  This kind of systems-level programming is powerful, but very error-prone, since it decomposes a high-level data flow into low-level system events that communicate
through shared state. 
Sometimes this style is necessary, but here it is not.

Our program instead eschews that more cumbersome programming style for this more natural, _direct_ style, where each request resembles an ordinary function call. 
This simpler, stylized programming form has become increasingly popular for expressing practical systems that interact with an _external environment_, as most modern software does today.
However, it requires special compiler and type-system support, as we discuss in more detail below.

[[pitch-async-behavior]]
=== Support for _asynchronous_ behavior

In an _asynchronous_ computing setting, a program and its running environment are permitted to perform _internal computations_ that occur _concurrently_ with one another.

Specifically, asynchronous programs are ones where the program's requests of its environment do not (necessarily) require the program to wait for the environment.
In the meantime, the program is permitted to make internal progress within this environment while the environment proceeds to complete the request. In the example, above, the program issues the second request before waiting for the first request to complete.

Symmetrically, the environment's requests of the program do not (necessarily) require the environment to wait for the program's answer: the environment can make external progress while the answer is produced.

We do not show an example of this "`notify`" pattern above, since it uses callbacks (and _higher-order_ functions and control flow) and is thus more complex.

[[pitch-async]]
=== Syntactic forms `async` and `await`

To address the need for clarity and simplicity, {proglang} adopts the increasingly-common program constructs `async` and `await`, which afford the programmer a _structured_ language for describing potentially-complex asynchronous dependency graphs.

The link:language-manual{outfilesuffix}#exp-async[async] syntax introduces futures. A future value
represents a _"`promise`" of a result that will be delivered, asynchronously, sometime in the future_ (not shown in the first example above).
You'll learn more about futures when we introduce actors in link:actors-async{outfilesuffix}[Actors and async data].

Here, we merely use the ones that arise from calling `service1.computeAnswer(params)` and
`service2.computeAnswer(params)`.

The syntax `await` synchronizes on a future, and suspends computation until the future is completed by its producer.
We see two uses of `await` in the example above,
to obtain the results from two calls to services.

When the developer uses these keywords, the compiler transforms the program as necessary, often doing complex transformations to the program's control- and data-flow that would be tedious to perform by hand in a purely synchronous language.
Meanwhile, the type system of {proglang} enforces certain correct usage patterns for these constructs, including that types flowing between consumers and producers always agree, and that the types of data sent among services are permitted to flow there, and do not (for example) contain link:mutable-state{outfilesuffix}[private mutable state].

[[pitch-types]]
=== Types are static

Like other modern programming languages, {proglang} permits each variable to carry the value of a function, object, or a primitive datum (for example, a string, word, or integer).
Other link:basic-concepts{outfilesuffix}#intro-values[types of values] exist too, including records, tuples, and "`tagged data`" called _variants_.

{proglang} enjoys the formal property of type safety, also known as _type soundness_.
We often summarize this idea with the phrase: link:basic-concepts{outfilesuffix}#intro-type-soundness[Well-typed {proglang} programs don't go wrong], meaning that the only operations that will be performed on data are those permitted by its
static type.

For example, each variable in a {proglang} program carries an associated _type_, and this type is known _statically_, before the program executes.
Each use of each variable is checked by the compiler to prevent runtime type errors, including null reference errors, invalid field access and the like.

In this sense, {proglang} types provide a form of _trustworthy, **compiler-verified** documentation_ in the program source code.

As usual, dynamic testing can check properties that are beyond the reach of the {proglang} type system.
While modern, the {proglang} type system is intentionally _not_ "`advanced`" or particularly exotic.
Rather, the type system of {proglang} integrates standard concepts from modern, but well-understood, link:about-this-guide{outfilesuffix}#modern-types[practical type systems] to provide an approachable, expressive yet safe language for programming general-purpose, distributed applications.
////