= Motoko プログラミング言語
:page-layout: default
:proglang: Motoko
:platform: Internet Computer blockchain network
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[IMPORTANT]
=====================================================================
{proglang} プログラミング言語は、 {sdk-short-name} のリリースや、 {proglang} コンパイラのアップデートを経て進化を続けています。
新しい機能を試したり、何が変わったのかを知るために、定期的に戻って確認しに来ましょう。
=====================================================================

{proglang} プログラミング言語は、Internet Computer ブロックチェーンネットワーク上で動く次世代の Dapps をビルドしたい開発者のための、新しく現代的で型安全な言語です。
{proglang} は、{IC} のユニークな機能をサポートし、親しみやすいけど頑丈なプログラミング環境を提供するよう、特別に設計されています。
新しい言語として {proglang} は、新たな機能や改善のサポートを経て進化し続けています。

{proglang} コンパイラ、ドキュメント、また他のツールは、 https://github.com/dfinity/motoko[オープンソース] であり、Apache 2.0 ライセンスのもとでリリースされています。コントリビュートは歓迎です。

[.cards.cards-4.personas.conceal-title]
{empty}

[.card]
== ネイティブ Canister スマートコントラクトサポート

{proglang} は、{IC} Canister スマートコントラクトをネイテイブサポートしています。

Canister スマートコントラクト (または略して Canister) は、 {proglang} Actor として表されます。 Actor とは、そのステートを完全にカプセル化して、非同期メッセージでのみ別の Actor との通信を行う自律的なオブジェクトです。

[source#counter,motoko]
----
include::../examples/Counter.mo[]
----

[.card]
== ダイレクトスタイルでシーケンシャルにコードを書く

{IC} 上では、Canisters は他の Canisters と非同期のメッセージを送ることでコミュニケーションができます。

非同期のプログラミングは難しいので、{proglang} はより単純なシーケンシャルスタイルでコードを書くことを可能にしています。非同期のメッセージは _future_ を返す関数呼び出しであり、`await` コンストラクトは future が完了するまで処理を延期することを許可します。この単純な機能は、他の言語でも不適切である非同期プログラミングでの"コールバック地獄"を回避します。

[source.include_counter,motoko]
----
include::../examples/factorial.mo[lines=9..-1]
----


[.card]
== 現代的な型システム

{proglang} は、JavaScript や他の有名言語と直感的に馴染みやすくなるよう設計されていますが、構造的型、ジェネリクス、バリアント型、または静的なパターンマッチングのような現代的な機能も提供します。

[source,motoko]
----
include::../examples/tree.mo[]
----

[.card]
== 自動生成の IDL ファイル

{proglang} Actor は、引数と返り値の型を示す関数として、常に型付けされたインターフェースをクライアントに、提供しています。

{proglang} コンパイラー（かつ SDK ）は、Candid と呼ばれる言語に依存しないフォーマットでこのインターフェースを出力するので、Candid をサポートしている別の Canisters やブラウザ上のコードやスマートフォンアプリは、Actor のサービスを利用することができます。{proglang} コンパイラは、Candid ファイルを使用したり生成したりすることができ、{proglang} にシームレスに（ Candid をサポートしている）他の言語で実装された Canister と接続することを可能にします。

例えば、上で示した {proglang} の `+Counter+` Actor は、次に続く Candid インターフェースを持っています。

[source,candid]
....
service Counter : {
  inc : () -> (nat);
}
....

[.card]
== 直交永続性

{IC} は、作動している Canister のメモリと他のステートも保持しています。それゆえ、Motoko Actor のステートは、そのインメモリデータ構造も含め永久に残り続けます。Actor のステートは、それぞれのメッセージと共に復元することや外部ストレージに保存することを明確に必要としていません。

例えば、シーケンシャルなIDをテキストの名前に割り当てる次の `Registry` Actor (Canister) では、Actor のステートがたくさんの {IC} ノードマシーンで複製されたもので、一般的にメモリ内にはいないれども、ハッシュテーブルのステートはコールを介して保存されています。

[source,motoko]
----
include::../examples/Registry.mo[]
----

[.card]
== アップグレード

{proglang} は、Canister のコードをアップグレードするとき Canister のデータを保持できることを許可する言語機能を含めた、直交永続性を活用するのを助ける数多くの機能を提供しています。

例えば、{proglang} は、ある変数を `stable` として宣言することができます。 `stable` 変数の値は、 Canister アップグレードでも自動的に保持されます。

stable カウンターを考えてみましょう。

[source,motoko]
----
include::../examples/StableCounter.mo[]
----

インストール後に _n_ 回インクリメントされ、その後中断することなく、より多機能な実装へとアップグレードすることができます。

[source,motoko]
----
include::../examples/StableCounterUpgrade.mo[]
----

`+value+` は `stable` として宣言されていたので、現在のステートやサービスの n はアップグレードの後でも保持されています。カウンティングは、0から再度始まるのではなく、n 回目から始まります。

その新しいインターフェースは過去のものと互換性がありますので、既に存在している Canister に関するクライアントは動作を続けていきますが、新しいクライアントは、アップグレードした機能を最大限利用することもできます。（追加の `reset` 機能）

stable な変数の使用のみでは解決できないシナリオのために、{proglang} は、アップグレードの前後で即座に動作するかつ任意のステートを静的な変数にすることを許可する、ユーザーが定義できるアップグレードフックを提供しています。


[.card]
== さらなる機能

{proglang} は、サブタイピング、任意精度演算、またはガベージコレクションを含めた、多くの開発者の生産性を上げる機能を提供しています。

{proglang} は、スマートコントラクト Canister を導入するためだけの言語ではなく、またそうであることを意図していません。もしあなたのニーズを満たさない時のために、Rust プログラミング言語の CDK があります。
私達の目標は、言語に左右されない Candid インターフェースを通し、他国の Canister スマートコントラクトと一緒に {IC} 上で動作する Canister スマートコントラクトを、いかなる言語でも作成できるようにすることです。

そのオーダーメイド設計は、少なくともしばらくの間 {proglang} が {IC} 上でのコーディングにおいて最も簡単かつ安全な言語であろうことを意味しています。

////
= Motoko Programming Language
:page-layout: default
:proglang: Motoko
:platform: Internet Computer blockchain network
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[IMPORTANT]
=====================================================================
The {proglang} programming language continues to evolve with each release of the {sdk-short-name} and with ongoing updates to the {proglang} compiler.
Check back regularly to try new features and see what's changed.
=====================================================================

The {proglang} programming language is a new, modern and type safe language for developers who want to build the next generation of distributed applications to run on the Internet Computer blockchain network.
{proglang} is specifically designed to support the unique features of the {IC} and to provide a familiar yet robust programming environment.
As a new language, {proglang} is constantly evolving with support for new features and other improvements.

The {proglang} compiler, documentation and other tooling is https://github.com/dfinity/motoko[open source] and released under the Apache 2.0 license. Contributions are welcome.

[.cards.cards-4.personas.conceal-title]
{empty}

[.card]
== Native canister smart contract support


{proglang} has native support for {IC} canister smart contracts.

A canister smart contract (or canister for short) is expressed as a {proglang} actor. An actor is an autonomous object that fully encapsulates its state and communicates with other actors only through asynchronous messages.

[source#counter,motoko]
----
include::../examples/Counter.mo[]
----

[.card]
== Code sequentially in direct style

On the {IC}, canisters can communicate with other canisters by sending asynchronous messages.

Asynchronous programming is hard, so {proglang} enables you to author asynchronous code in much simpler, sequential style. Asynchronous messages are function calls that return a _future_, and the `await` construct allows you to suspend execution until a future has completed. This simple feature avoids the  "callback hell" of explicit asynchronous programming in other languages.

[source.include_counter,motoko]
----
include::../examples/factorial.mo[lines=9..-1]
----


[.card]
== Modern type system

{proglang} has been designed to be intuitive to those familiar with JavaScript and other popular languages, but offers modern features such as sound structural types, generics, variant types, and statically checked pattern matching.

[source,motoko]
----
include::../examples/tree.mo[]
----

[.card]
== Autogenerated IDL files

A {proglang} actor always presents a typed interface to its clients as a suite of named functions with argument and (future) result types.

The {proglang} compiler (and SDK) can emit this interface in a language neutral format called Candid, so other canisters, browser resident code and smart phone apps that support Candid can use the actor's services.
The {proglang} compiler can consume and produce Candid files, allowing {proglang} to seamlessly interact with canisters implemented in other programming languages (provided they support Candid).

For example, the previous {proglang} `+Counter+` actor has the following Candid interface:

[source,candid]
....
service Counter : {
  inc : () -> (nat);
}
....

[.card]
== Orthogonal persistence

The {IC} persists the memory and other state of your canister as it executes. Thus the state of a Motoko actor, including its in-memory data structures, survive indefinitely.
Actor state does not need to be explicitly "restored" and "saved" to external storage, with every message.

For example, in the following `Registry` actor (canister), that assigns sequential IDs to textual names, the state of the hash table is preserved across calls, even though the state of the actor
is replicated across many {IC} node machines, and typically not resident in memory.

[source,motoko]
----
include::../examples/Registry.mo[]
----

[.card]
== Upgrades

{proglang} provides numerous features to help you leverage orthogonal persistence, including language features that allow you to retain a canister's data as you upgrade the code of the canister.

For example, {proglang} lets you declare certain variables as `stable`. The values of `stable` variables are automatically preserved across canister upgrades.

Consider a stable counter:

[source,motoko]
----
include::../examples/StableCounter.mo[]
----

It can be installed, incremented _n_ times, and then upgraded, without interruption, to, for example, the richer implementation:

[source,motoko]
----
include::../examples/StableCounterUpgrade.mo[]
----

Because `+value+` was declared `stable`, the current state, _n_, of the service is retained after the upgrade. Counting will continue from _n_, not restart
from `0`.

Because the new interface is compatible with the previous one, existing clients referencing the canister will continue to work, but new clients will be able to exploit its upgraded functionality
(the additional `reset` function).

For scenarios that can't be solved using stable variables alone, {proglang} provides user-definable upgrade hooks that run immediately before and after upgrade,
and allow you to migrate arbitrary state to stable variables.


[.card]
== And more ...

{proglang} provides many other developer productivity features, including subtyping, arbitrary precision arithmetic and garbage collection.

{proglang} is not, and is not intended to be, the only language for implementing canister smart contracts.
If it doesn't suit your needs, there is a canister development kit (CDK) for the Rust programming language.
Our goal is to enable any language (with a compiler that targets WebAssembly) to be able to produce canister smart contracts that run on the {IC} and interoperate
with other, perhaps foreign, canister smart contracts through language neutral Candid interfaces.

Its tailored design means {proglang} should be the easiest and safest language for coding on the {IC}, at least for the forseeable future.

////
